doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - django
    - celery
autodetect: no
requirements:
    - requirements.txt

ignore-paths:
    - docs
    - django_documentos/migrations

#ignore-patterns:
#    - ^example/doc_.*\.py$
#    - (^|/)docs(/|$)
pylint:
  disable:
    - E1002
    - C1001
